server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: test
    password: test
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true